version: '3'
services:
    python-app:
        build: ./app
        environment: 
            REDIS_PORT: 6379
            REDIS_URL: redis-test
        ports: 
            - 8000:80
    redis-test:
        image: redis
        ports: 
            - 6379:6379
